name: Stand.fm RSS Monitor

on:
  schedule:
    # 毎時実行 (UTC基準。日本時間では午前9時, 10時, ...)
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行を許可

jobs:
  monitor_rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write # rss_monitor_state.json をコミットするために必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # ローカル環境に合わせる

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser selenium

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2 # ChromeDriverをインストールしPATHに追加

      - name: Run RSS Monitor script
        env:
          PYTHONIOENCODING: 'utf-8' # 文字化け防止のため
        run: python src/rss_monitor.py

      - name: Commit and push state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # rss_monitor_state.json はリポジトリのルートにある想定
          if [ -f rss_monitor_state.json ]; then
            git add rss_monitor_state.json
            # 変更があった場合のみコミット
            if ! git diff --staged --quiet; then
              git commit -m "Update rss_monitor_state.json [skip ci]"
              git push
            else
              echo "No changes to rss_monitor_state.json to commit."
            fi
          else
            echo "rss_monitor_state.json not found. Skipping commit."
          fi
